In [1]:

# EXPERIMENT 11: Pandas DataFrame Functions

import pandas as pd
import numpy as np

# Step 1: Create sample employee data
employees = {
    "EmpID": [1, 2, 3, 4, 5],
    "Name": ["Smith", "Jones", "Taylor", "Patel", "Kumar"],
    "Age": [25, 30, 28, 35, 32],
    "Salary": [50000, 60000, 55000, 70000, 65000]
}

df = pd.DataFrame(employees)

# Step 2: Save data to CSV
df.to_csv("employees.csv", index=False)
print("employees.csv created successfully!")

# Step 3: Read CSV file
df = pd.read_csv("employees.csv")

# Step 4: Display the DataFrame
print("\nEmployee DataFrame:")
display(df)

# Step 5: Display information
print("\nDataFrame Information:")
df.info()

# Step 6: Display first and last rows
print("\nFirst five rows:")
display(df.head())

print("\nLast five rows:")
display(df.tail())

# Step 7: Display number of rows and columns
print("\nShape:", df.shape)

# Step 8: Select a single column
print("\nEmployee Names:")
print(df["Name"])

# Step 9: Select multiple columns
print("\nName and Salary:")
display(df[["Name", "Salary"]])

# Step 10: Select rows using a condition
print("\nEmployees with Salary greater than 55000:")
display(df[df["Salary"] > 55000])

# Step 11: Add a new column
df["Department"] = [
    "IT", "HR", "Sales", "IT", "Finance"
]
print("\nAfter adding Department:")
display(df)

# Step 12: Rename a column
df = df.rename(columns={"Name": "EmployeeName"})
print("\nAfter renaming Name:")
display(df)

# Step 13: Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Step 14: Sort by salary
print("\nSorted by Salary:")
display(df.sort_values(by="Salary"))

# Step 15: Group employees by department
print("\nEmployees in Each Department:")
print(df.groupby("Department").size())

# Step 16: Calculate statistical measures
print("\nMean Salary:", df["Salary"].mean())
print("Median Salary:", df["Salary"].median())
print("Maximum Salary:", df["Salary"].max())
print("Minimum Salary:", df["Salary"].min())
print("Standard Deviation:", df["Salary"].std())

# Step 17: Display descriptive statistics
print("\nDescriptive Statistics:")
display(df.describe())

# Step 18: Convert DataFrame to NumPy array
print("\nDataFrame as NumPy Array:")
print(df.to_numpy())

# Step 19: Save the final DataFrame
df.to_csv("employees_processed.csv", index=False)

print("\nExperiment 11 completed successfully!")

employees.csv created successfully!

Employee DataFrame:

   EmpID    Name  Age  Salary
0      1   Smith   25   50000
1      2   Jones   30   60000
2      3  Taylor   28   55000
3      4   Patel   35   70000
4      5   Kumar   32   65000

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   EmpID   5 non-null      int64
 1   Name    5 non-null      object
 2   Age     5 non-null      int64
 3   Salary  5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

First five rows:

   EmpID    Name  Age  Salary
0      1   Smith   25   50000
1      2   Jones   30   60000
2      3  Taylor   28   55000
3      4   Patel   35   70000
4      5   Kumar   32   65000

Last five rows:

   EmpID    Name  Age  Salary
0      1   Smith   25   50000
1      2   Jones   30   60000
2      3  Taylor   28   55000
3      4   Patel   35   70000
4      5   Kumar   32   65000

Shape: (5, 4)

Employee Names:
0     Smith
1     Jones
2    Taylor
3     Patel
4     Kumar
Name: Name, dtype: object

Name and Salary:

     Name  Salary
0   Smith   50000
1   Jones   60000
2  Taylor   55000
3   Patel   70000
4   Kumar   65000

Employees with Salary greater than 55000:

   EmpID   Name  Age  Salary
1      2  Jones   30   60000
3      4  Patel   35   70000
4      5  Kumar   32   65000

After adding Department:

   EmpID    Name  Age  Salary Department
0      1   Smith   25   50000         IT
1      2   Jones   30   60000         HR
2      3  Taylor   28   55000      Sales
3      4   Patel   35   70000         IT
4      5   Kumar   32   65000    Finance

After renaming Name:

   EmpID EmployeeName  Age  Salary Department
0      1        Smith   25   50000         IT
1      2        Jones   30   60000         HR
2      3       Taylor   28   55000      Sales
3      4        Patel   35   70000         IT
4      5        Kumar   32   65000    Finance

Missing Values:
EmpID           0
EmployeeName    0
Age             0
Salary          0
Department      0
dtype: int64

Sorted by Salary:

   EmpID EmployeeName  Age  Salary Department
0      1        Smith   25   50000         IT
2      3       Taylor   28   55000      Sales
1      2        Jones   30   60000         HR
4      5        Kumar   32   65000    Finance
3      4        Patel   35   70000         IT

Employees in Each Department:
Department
Finance    1
HR         1
IT         2
Sales      1
dtype: int64

Mean Salary: 60000.0
Median Salary: 60000.0
Maximum Salary: 70000
Minimum Salary: 50000
Standard Deviation: 7905.694150420948

Descriptive Statistics:

          EmpID        Age       Salary
count  5.000000   5.000000      5.00000
mean   3.000000  30.000000  60000.00000
std    1.581139   3.807887   7905.69415
min    1.000000  25.000000  50000.00000
25%    2.000000  28.000000  55000.00000
50%    3.000000  30.000000  60000.00000
75%    4.000000  32.000000  65000.00000
max    5.000000  35.000000  70000.00000

DataFrame as NumPy Array:
[[1 'Smith' 25 50000 'IT']
 [2 'Jones' 30 60000 'HR']
 [3 'Taylor' 28 55000 'Sales']
 [4 'Patel' 35 70000 'IT']
 [5 'Kumar' 32 65000 'Finance']]

Experiment 11 completed successfully!