In [ ]:

# EXPERIMENT 15: Data Preprocessing in Data Science

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer

# Step 1: Create sample dataset with missing values
data = {
    "Country": [
        "France", "Spain", "Germany", "Spain", "Germany",
        "France", "Spain", "France", None, "France"
    ],
    "Age": [44, 27, 30, 38, 40, 35, np.nan, 48, 50, 37],
    "Salary": [
        72000, 48000, 54000, 61000, np.nan,
        58000, 52000, 79000, 83000, 67000
    ],
    "Purchased": [
        "No", "Yes", "No", "No", "Yes",
        "Yes", "No", "Yes", "No", "Yes"
    ]
}

df = pd.DataFrame(data)

# Step 2: Save the dataset as CSV
df.to_csv("pre-process_datasample.csv", index=False)
print("CSV file created successfully!")

# Step 3: Read the CSV file
df = pd.read_csv("pre-process_datasample.csv")

print("\nOriginal Dataset:")
display(df)

# Step 4: Display dataset information
print("\nDataset Information:")
df.info()

# Step 5: Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Step 6: Fill missing Country values using mode
df["Country"] = df["Country"].fillna(df["Country"].mode()[0])

# Step 7: Fill missing Age values using median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Step 8: Fill missing Salary values using mean
df["Salary"] = df["Salary"].fillna(round(df["Salary"].mean()))

print("\nDataset after handling missing values:")
display(df)

# Step 9: Encode categorical data using One-Hot Encoding
df_encoded = pd.get_dummies(
    df,
    columns=["Country"],
    dtype=int
)

# Step 10: Encode Purchased column
df_encoded["Purchased"] = df_encoded["Purchased"].map(
    {"No": 0, "Yes": 1}
)

print("\nDataset after encoding categorical variables:")
display(df_encoded)

# Step 11: Standardize numerical features
standard_scaler = StandardScaler()

df_encoded[["Age", "Salary"]] = standard_scaler.fit_transform(
    df_encoded[["Age", "Salary"]]
)

print("\nDataset after Standard Scaling:")
display(df_encoded)

# Step 12: Apply Min-Max Scaling to numerical features
minmax_scaler = MinMaxScaler()

df_minmax = df.copy()
df_minmax[["Age", "Salary"]] = minmax_scaler.fit_transform(
    df_minmax[["Age", "Salary"]]
)

print("\nDataset after Min-Max Scaling:")
display(df_minmax)

# Step 13: Save the preprocessed dataset
df_encoded.to_csv("preprocessed_data.csv", index=False)

print("\nExperiment 15 completed successfully!")
print("Output saved as preprocessed_data.csv")

CSV file created successfully!

Original Dataset:

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8      NaN  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    9 non-null      object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

Missing Values:
Country      1
Age          1
Salary       1
Purchased    0
dtype: int64

Dataset after handling missing values:

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63778.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8   France  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Dataset after encoding categorical variables:

    Age   Salary  Purchased  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0          0               1                0              0
1  27.0  48000.0          1               0                0              1
2  30.0  54000.0          0               0                1              0
3  38.0  61000.0          0               0                0              1
4  40.0  63778.0          1               0                1              0
5  35.0  58000.0          1               1                0              0
6  38.0  52000.0          0               0                0              1
7  48.0  79000.0          1               1                0              0
8  50.0  83000.0          0               1                0              0
9  37.0  67000.0          1               1                0              0

Dataset after Standard Scaling:

,Age,Salary,Purchased,Country_France,Country_Germany,Country_Spain
0,0.769734,0.749471,0,1,0,0
1,-1.699225,-1.438180,1,0,0,1
2,-1.263526,-0.891268,0,0,1,0
3,-0.101663,-0.253202,0,0,0,1
4,0.188803,0.000018,1,0,1,0
5,-0.537362,-0.526659,1,1,0,0
6,-0.101663,-1.073572,0,0,0,1
7,1.350666,1.387536,1,1,0,0
8,1.641132,1.752145,0,1,0,0
9,-0.246896,0.293710,1,1,0,0

Dataset after Min-Max Scaling:

   Country       Age    Salary Purchased
0   France  0.739130  0.685714        No
1    Spain  0.000000  0.000000       Yes
2  Germany  0.130435  0.171429        No
3    Spain  0.478261  0.371429        No
4  Germany  0.565217  0.450800       Yes
5   France  0.347826  0.285714       Yes
6    Spain  0.478261  0.114286        No
7   France  0.913043  0.885714       Yes
8   France  1.000000  1.000000        No
9   France  0.434783  0.542857       Yes

Experiment 15 completed successfully!
Output saved as preprocessed_data.csv